# This section declares settings for the server.
[server]
host = "127.0.0.1"      # server host
port = 8080             # server port

# This section declares setting for the database.
[database]
path = "database"       # database path

# This section declares settings for recommendation.
[recommend]
model = "bpr"           # recommendation model for personal ranking
top_n = 1024             # the number of cached recommendations/neighbor/latest/popular items
update_threshold = 10   # update recommendation when more than 10 recommendations are cosumed
train_threshold = 100   # retrain model when more than 100 ratings are added
check_period = 7        # check for update every one minute
similarity = "tag"  # similarity metric for neighbors
fit_jobs = 8            # concurrent jobs for fitting
update_jobs = 9        # concurrent jobs for predict
collectors = ["pop", "latest", "neighbor"]

# This section declares hyperparameters for the recommendation model.
[params]
lr = 0.05               # learning rate
reg = 0.01              # regularization strength
n_epochs = 100          # number of epochs
n_factors = 10          # number of factors
random_state = 21       # random state (seed)
use_bias = false        # use bias
init_mean = 0.0         # mean of gaussian initial parameter
init_std = 0.001        # standard deviation of gaussian initial parameter
alpha = 1.0             # alpha value, depend on context