# This section declares settings for the server.
[server]
host = "127.0.0.1"      # server host
port = 8080             # server port

# This section declares setting for the database.
[database]
file = "gorse.db"       # database file

# This section declares settings for recommendation.
[recommend]
model = "als"           # recommendation model
cache_size = 100        # the number of cached recommendations
update_threshold = 10   # update model when more than 10 ratings are added
check_period = 1        # check for update every one minute
similarity = "pearson"  # similarity metric for neighbors
fit_jobs = 1            # concurrent jobs for fitting

# This section declares hyperparameters for the recommendation model.
[params]
n_factors = 20          # the number of latent factors
reg = 0.015             # regularization strength
n_epochs = 10           # the number of learning epochs