name: 'assign issues'

on:
  issue_comment:
    types: [created, edited]

jobs:
  assign_issues:
    name: Assign issues
    if: ${{ !github.event.issue.pull_request && github.event.comment.body == '/assign' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          assign $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
