name: build

on:
  push:
    branches:    
      - master

jobs:
  docker_images:
    name: docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [gorse-master, gorse-server, gorse-worker, gorse-in-one]
    steps:
      - name: Pull source
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: cmd/${{ matrix.image }}/Dockerfile
          push: true
          tags: zhenghaoz/${{ matrix.image }}:nightly
          cache-from: type=gha
          cache-to: type=gha,mode=max
